services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $assetsContext: '@contao.assets.assets_context'

    Bwein\DismissableBannerElement\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection}'
